[Server]
Addr = "0.0.0.0"
Port = "3333"
Secret = "megaSecret"
AssetsDir ="./assets"

[Database]
DSN="postgres://postgres:12345@db:5432/postgres?sslmode=disable"

[Cashbox]
InHash="asdfsfsfojnegounegiuegngeitbe"
OutHash="orngiurinuirgniurnortbnrtigm"
ServerAddr="http://cash-api:7777/reg"
